[package]
name = "volt"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cpal = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
image = { version = "0.25.5", features = ["jpeg", "png"] }
open = "5.3.2"
rustfft = "6.2.0"
serde = "1.0.217"
strum = { version = "0.27.2", features = ["derive"] }
tap = "1.0.1"
blerp = { path = "../blerp" }
volt-waveform = { workspace = true }
human-panic = "2.0.2"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
notify = { version = "8.0.0", features = ["crossbeam-channel"] }
crossbeam-channel = "0.5.14"
pastey = "0.1.1"
unicode-truncate = "2.0.0"
symphonia = { version = "0.5.4", features = ["all"] }
strsim = "0.11.1"
unhygienic2 = "0.1.0"
gpui = { git = "https://github.com/gpui-ce/gpui-ce" }
gpui_platform = { git = "https://github.com/gpui-ce/gpui-ce" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "277f220a6196572116a8fd84fba6c36187094cab", features = ["tree-sitter-languages"] }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "277f220a6196572116a8fd84fba6c36187094cab", package = "gpui-component-assets" }
sum_tree = { git = "https://github.com/zed-industries/zed" }
anyhow = { workspace = true }
resvg = "0.47.0"
tiny-skia = "0.12.0"
smallvec = { version = "1.6", features = ["union", "const_new"] }

# TEMPORARY FIX: Fix some platform support
[target.'cfg(target_os = "linux")'.dependencies]
wgpu = "25"

[target.'cfg(target_os = "macos")'.dependencies]
core-text = ">=21.0.0, <21.1.0"