[package]
name = "blerp"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cpal = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
crossbeam-channel = "0.5.15"
parking_lot = "0.12.4"
ringbuf = "0.4.8"
symphonia = { version = "0.5.4", features = ["all"] }
tap = "1.0.1"
