[package]
name = "blerp"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cpal = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
crossbeam-channel = "0.5.15"
parking_lot = "0.12.4"
ringbuf = "0.4.8"
symphonia = { version = "0.5.4", features = ["all"] }
tap = "1.0.1"
timestretch = "0.4.0"
ssstretch = "0.1.0"
tdpsola = "0.1.0"
ness_stretch = "0.5.1"
dasp_interpolate = "0.11.0"
rustfft = "6.4.1"
creek = "1.2.3"
rubato = "2.0.0"
